### ISSUE TITLE
val() is not returning values selected

### ISSUE THREAD

**Issue by kaushikgopalan** [quarterto/Elessar#106]
Hi,

I am using Elessar for selecting a set of ranges. I dont get the values that I have selected, when I try to use the function .val().

Code snippet: 
            console.log('rangebar value:');
            console.log(rangeBars);// for testing.. gives the entire div as output. not needed.
            
            console.log(rangeBars.val());// not working.

I am using chromium browser in ubuntu 14.04.

**Comment by quarterto** [comment]
Hi @kaushikgopalan, thanks for the report. What is `.val()` actually returning? Could you post your rangebar setup code?

**Comment by kaushikgopalan** [comment]
Hi @quarterto ,

my setup code:
 rangeBars=RangeBar({
            min: minVal,//moment().startOf('day').format('LLLL'),
            max: maxVal,//moment().startOf('day').add(1, 'day').format('LLLL'),
            valueFormat: function(ts) {
                return ts;//moment(ts).format('LLLL');
            },
            valueParse: function(date) {
                return date;//moment(date).valueOf();
            },
            values: [
                [
                    minVal,//moment().startOf('day').format('LLLL'),
                    midVal//moment().startOf('day').add(1, 'hours').format('LLLL')
                ],

            ],
            label: function(a){return JSON.stringify(a)},
            snap: 0.5,//1000 * 60 * 15,
            minSize: 1,//1000 * 60 * 60,

            allowDelete:true,
            indicator:null

        }).on('changing', function(ev, ranges, changed) {
            console.log(changed);
            $('pre.changing').html(JSON.stringify(ranges,null,2));
        }).on('change', function(ev, ranges, changed) {
            console.log(changed);
            $('pre.changing').after($('<pre>').html('changed'+JSON.stringify(ranges,null,2)));
        }).$el;

**Comment by quarterto** [comment]
`.val()` is a method of the RangeBar object itself. You're returning `$el` which is just the element it generates and has no special properties or methods of its own. You need to do something like:

```js
var rangeBar = new RangeBar(...);
var rangeBarElement = rangeBar.$el;
// attach rangeBarElement somewhere
// later:
rangeBar.val();
```

**Comment by kaushikgopalan** [comment]
thanks a lot for the clarification :)
