### ISSUE TITLE
RangeBar is not defined

### ISSUE THREAD

**Issue by AnimaLupi** [quarterto/Elessar#110]
Hello,

I'm getting the error
`Uncaught ReferenceError: RangeBar is not defined`
when using the browser version of Elessar.

The issue can be reproduced by opening the index.html file in the demos dir.

Version 1.8.4 wasn't affected by this problem, so I guess it's either an issue introduced by 1.8.5 or maybe something gone wrong in building the dist files of latest version?

Thank you,

Andrea

**Comment by quarterto** [comment]
Good catch. I totally rewrote the build process in 724a77d and neglected to actually test the bundle :flushed: Turns out it's not actually exporting anything.

**Comment by quarterto** [comment]
I've fixed the bundle and republished the 1.8.5 tag. If you're using Bower you may need to run `bower cache clean elessar`

**Comment by AnimaLupi** [comment]
Thank you, it's working now!

Ciao,

Andrea
