### ISSUE TITLE
Humble targeting question

### ISSUE THREAD

**Issue by kirkbross** [quarterto/Elessar#84]
When I inspect a range, it just has the elessar-range and bar classes, but no id. 

How do I target individual ranges within a bar, for example to remove it. I saw rangebar.removeRange(id) in the closed issue but can't figure out how to actually make it work.

http://blog.153.io/Elessar/

**Comment by quarterto** [comment]
`removeRange` takes either a range index or range object. So, if you wanted to delete the 3rd range, you'd do `rangebar.removeRange(2)` or `rangebar.removeRange(rangebar.ranges[2])` (note that, as `removeRange` uses `indexOf`, the second style is redundant).

If you want to get the actual DOM element of an object, it's `$el`. So, for the rangebar, `rangebar.$el`; for a particular range, `rangebar.ranges[i].$el`.

I'll admit that the documentation is in a pretty terrible state, and needs improving (#80).
