### ISSUE TITLE
Separate start, end and length values?

### ISSUE THREAD

**Issue by kirkbross** [quarterto/Elessar#85]
Firstly... do you have a donation link on your site or elsewhere?

What is the best / smartest way to get the start and end times, and the length into their own elements within a range. I am able to insert elements into a range via ln 223 of elessar.js like this ...

initialize.super$.call(this, '<div class="elessar-range"><span class="start-time"/><span class="end-time"/><span class="elessar-barlabel">'); 

... but I suspect this is not the best way to do it. See this pic of what I'm trying to achieve.

![elessar](https://cloud.githubusercontent.com/assets/6109742/5713397/aaee6ba0-9a70-11e4-80d8-e1c78238b313.jpg)

**Comment by quarterto** [comment]
It should be possible to do this with the `htmlLabel` option, something like 
(assuming you're using Moment.js):

```javascript
new RangeBar({
  htmlLabel: true,
  label: function(val) {
    return '<span class="label-left">'  + val[0].format('h:mm A') + '</span>'
         + '<span class="label-right">' + val[1].format('h:mm A') + '</span>'
         + moment.duration(val[1].diff(val[0])).humanize();
  }
});
```

There's a Flattr link in the readme :)
