### ISSUE TITLE
Do something to (only) range currently being changed?

### ISSUE THREAD

**Issue by kirkbross** [quarterto/Elessar#86]
I am struggling (admittedly an intermediate js programmer) to implement range index to target specific ranges. For example, what would be the correct syntax if I wanted the range being changed to be red during changing and green when done changing. This does it to ALL the ranges, but I'd like to narrow it to only the range currently being dragged/changed:

```js
$(RangeBar).on( "changing", function() {
		$(this).find( ".elessar-range" ).css( "background", "red" )
	}).on( "change", function() {
		$(this).find( ".elessar-range" ).css( "background", "green" )
});
```

**Comment by quarterto** [comment]
The event handler function gets passed extra arguments: the event, the current value, and the range that is currently being changed. The events are fired on the rangebar object itself as well as on the element. You can access a range's element using `.$el`. So your example would look like:

```js
rangeBar.on( "changing", function(ev, val, range) {
        $(range.$el).css( "background", "red" )
    }).on( "change", function(ev, val, range) {
        $(range.$el).css( "background", "green" )
});
```

**Comment by kirkbross** [comment]
It's working for the 'on change' but strangely not for the the 'on changing' ... i.e. when I let go of the mouse it becomes green but does not turn red during the drag/change. Here's my full init:

$(function() {
    $("#rangebar").prepend(RangeBar({
        min: moment().startOf("day").format("LLLL"),
        max: moment().startOf("day").add(1, "day").format("LLLL"),
        valueFormat: function(ts) {
            return moment(ts).format("h:mm a");
        },
        valueParse: function(date) {
            return moment(date).valueOf();
        },
        htmlLabel: true,
        label: function(a) {
            return '<span class="range-start">' + a[0] + '</span>' + '<span class="range-end">' + a[1] + '</span><span class="range-duration">duration</span><br />' + '<span class="range-index">index of this range var</span>';
        },
        snap: 1000 * 60 * 15,
        minSize: 1000 * 60 * 30,
        bgLabels: 4,

    }).$el).on("changing", function(ev, val, range) {
        $(range.$el).css("background", "red");
    }).on("change", function(ev, val, range) {
        $(range.$el).css("background", "green");

    });
});

**Comment by quarterto** [comment]
Does it work if you attach the handlers directly to the rangebar? I.e.:

```js
$(function() {
    $("#rangebar").prepend(RangeBar({
      ...
    }).on("changing", function(ev, val, range) {
        $(range.$el).css("background", "red");
    }).on("change", function(ev, val, range) {
        $(range.$el).css("background", "green");
    }).$el);
});
```

---
p.s. for future reference, you can mark up code segments on Github with triple backticks:

    ```javascript
    function() {}
    ```

**Comment by kirkbross** [comment]
Yeah, that didn't work, BUT my broader code is a little more complex so I'm certain it's my error. Ultimately however, I am  trying to prepend rangebars in about a dozen divs (with unique IDs) using each() to iterate through. Like thus:

```javascript
$(function() {
    $(".elessar-ui").each(function() {
        var newRange = new RangeBar({
            min: moment().startOf("day").format("LLLL"),
            max: moment().startOf("day").add(1, "day").format("LLLL"),
            valueFormat: function(ts) {
                return moment(ts).format("h:mm a");
            },
            valueParse: function(date) {
                return moment(date).valueOf();
            },
            htmlLabel: true,
            label: function(a) {
                return '<span class="range-start">' + a[0] + '</span>' + '<span class="range-end">' + a[1] + '</span><span class="range-duration">Duration: (need h:mm duration of range here... moment.duration(val[1].diff(val[0])).humanize(); doesnt seem to work) </span><br />' + '<span class="range-cost">$.07</span>';
            },
            snap: 1000 * 60 * 15,
            minSize: 1000 * 60 * 30,
            bgLabels: 4,

        });
        // attach a rangebar to each div.elessar-ui (each of which has a unique id) 
        $(this).prepend(newRange.$el)
            .on("changing", function(ev, val, range) {
                $(range.$el).css("background", "red");
            })
            .on("change", function(ev, val, range) {
                $(range.$el).css("background", "green");

            });

    });
});
```

**Comment by quarterto** [comment]
That's a perfectly fine way of doing that.

**Comment by kirkbross** [comment]
Many thanks. I'll troubleshoot why .on("changing", ...)  isn't catching... surely a small, silly typo.

**Comment by kirkbross** [comment]
So... ditching the .$el worked. i.e., changing this:

```javascript
$(range.$el).css("background", "red");
```
... to this...
```javascript
$(range).css("background", "red");
```
did the trick. Not sure why...

**Comment by quarterto** [comment]
[Oops, yeah, sorry](https://github.com/quarterto/Elessar/blob/develop/lib/range.js#L128)

**Comment by kirkbross** [comment]
Here's my mostly-working version. 

http://k1r.com/elessar/

Final fixes I'm working on are:
* duration-- to display eg. 4 hours 15 minutes (where it currently returns "a few seconds") 
* when you click a gear icon, then the "Delete Range" button, to delete that range
* clear the entire schedule when you click the Clear Schedule button under the rangebar
