### ISSUE TITLE
Multiple valueFormats necessary?

### ISSUE THREAD

**Issue by kirkbross** [quarterto/Elessar#87]
Can you spot (without blood loss) why the below is returning "a few seconds" instead of the range duration in h:mm? (or preferable h + "hours " mm + "minutes").

(Note: Changing the valueFormat to format("LLLL") returns the duration in hours but returns all my other labels in long form)

```javascript
moment(a[1]).from(a[0], true)
```
In this RangeBar:

```javascript
var newRange = new RangeBar({
    min: moment().startOf("day").format("LLLL"),
    max: moment().startOf("day").add(1, "day").format("LLLL"),
    valueFormat: function(ts) {
        return moment(ts).format("h:mm a");
    },
    valueParse: function(date) {
        return moment(date).valueOf();
    },
    htmlLabel: true,
    label: function(a) {
        return '<span class="range-start">' + a[0] + '</span>' + '<span class="range-end">' + a[1] + '</span><span class="range-duration">' + moment(a[1]).from(a[0], true) + '</span><br />' + '<span class="range-cost">$.07</span>';
    },
    snap: 1000 * 60 * 15,
    minSize: 1000 * 60 * 30,
    bgLabels: 4,
    rangeClass: "bg-primary"

});
```
I also tried:

```javascript
moment.duration(a[1].diff(a[0])).humanize();
```
...but that breaks the rangebar...

Here is a pic of what a range looks like now:

![screen shot 2015-01-14 at 2 40 07 pm](https://cloud.githubusercontent.com/assets/6109742/5749294/832629fe-9bfc-11e4-9407-42e05faa4c8c.png)

**Comment by quarterto** [comment]
The argument passed to `label` is already formatted. You'll have to parse it, I think this should work:

```js
label: function(a) {
  return moment(this.options.valueParse(a[1])).from(this.options.valueParse(a[0]), true);
},
```

**Comment by kirkbross** [comment]
hmmm... that breaks the range... (it initializes but you can't create any ranges on the rangebar). 

This is assuming I leave the valueFormat and valueParse as I have them... i.e.

```javascript
valueFormat: function(ts) {
                return moment(ts).format("h:mm a");
            },
            valueParse: function(date) {
                return moment(date).valueOf();
            },
```
