### ISSUE TITLE
Remove existing slider?

### ISSUE THREAD

**Issue by yubozhao** [quarterto/Elessar#91]
Hi @quarterto 

This is an awesome plugin, thank you!   Just wondering how would you remove an existing slider from elessar bar?  To use your hour example, if I want to remove an slider from it.  How would it works?

**Comment by quarterto** [comment]
See #22. If you set `allowDelete: true` in the options, you can double-middle-click to remove a range. Alternatively you can implement your own event handler and call `rangebar.removeRange(range)`.
