### ISSUE TITLE
bower main

### ISSUE THREAD

**Issue by TrySound** [quarterto/Elessar#93]
Change please main filed to non-minified version

**Comment by TrySound** [comment]
And add css file to main

**Comment by quarterto** [comment]
I will do this in the future, but since this is a breaking change, it will have to wait for Elessar 2.0.

**Comment by TrySound** [comment]
Breaking change, realy?

**Comment by quarterto** [comment]
Yes.

**Comment by TrySound** [comment]
@quarterto And what it can break?

**Comment by quarterto** [comment]
People who expect the `main` field to be a string, not an array. People who expect the `main` field to point to the minified version.

**Comment by TrySound** [comment]
@quarterto 

https://github.com/bower/bower.json-spec#main
[main-bower-files](https://github.com/ck86/main-bower-files) can process both types.

I except working solution, not part of something.

**Comment by quarterto** [comment]
And for people not using `main-bower-files`? This is a breaking change. This is not up for discussion.

**Comment by TrySound** [comment]
@quarterto Those who use bower.main not use just your lib and they can process both types. But usually nobody parses bower files, it is processed by external modules that can support both types like main-bower-files.
