### ISSUE TITLE
Joining consecutive ranges results in shifting of data (when working with whole number ranges) 

### ISSUE THREAD

**Issue by web-engineer** [quarterto/Elessar#94]
I wrote a very simple handler to conjoin blocks after a timeout when they are consecutive (ie. to achieve the  affect of waiting a 1/2 second, assume the user wants one contiguous block now two)

I'm using an integer based range representing minuites of an hour - if I have 3 or four single minuites with a minute gap at the end and two ranges eariler in the sequence then attempting to change the array of values using rangebar.val(myarray) results in some of the later ranges shifting.

Calling val() as a getter returns an array different to the one that was set.

Calling val with the array after a momentary timeout corrects the problem - this olny gets fixes if I've attempted to set the value twice?

Acid test -

With a document open with jQuery and Elessar included in the head run the following in console -
```
var rangeBar = RangeBar({
values: [[0,14],[14,26],[40,41],[42,43],[44,45],[46,47],[48,49],[50,51]],
readonly: false, min: 0, max:51, snap: 1, minSize: 1,
valueFormat: function (n) { return Math.round(n); },
valueParse: function (n) { return Math.round(n); }});
						
$('body').html(rangeBar.$el);

rangeBar.val([[0,26],[40,41],[42,43],[44,45],[46,47],[48,49],[50,51]]);

console.info(JSON.stringify(rangeBar.val()));
```
output
```
[[0,26],[39,40],[41,42],[43,44],[45,46],[47,48],[50,51]]
```
Which is not what we set it to! - range 45 to 46 was not in our previous call!

The fix is to set the value again after a small timeout (not immediate) and it corrects the display - but this feels super kludgy... any ideas appreciated? Great component otherwise.

The above was ran within my site which has some other stying to make it work - however - it still behaves the same on your own demo page with the adition of the bar and rangeclass properties - i.e. -

http://blog.153.io/Elessar/

Open console and run -
```
var rangeBar = RangeBar({
values: [[0,14],[14,26],[40,41],[42,43],[44,45],[46,47],[48,49],[50,51]],
readonly: false, min: 0, max:51, snap: 1, minSize: 1, barClass: 'progress', rangeClass: 'bar',
valueFormat: function (n) { return Math.round(n); },
valueParse: function (n) { return Math.round(n); }});

$('body').html(rangeBar.$el);

rangeBar.val([[0,26],[40,41],[42,43],[44,45],[46,47],[48,49],[50,51]]);

JSON.stringify(rangeBar.val());
```
yeilds
```
[[0,26],[39,40],[41,42],[43,44],[45,46],[47,48],[50,51]]
```
Still - we now have 39 to 40 in our range?

Am I missing something? really kludgy fix is to run the same set value after a timeout of 1ms - that does fix things but has been my only way to make this work.

**Comment by woody2** [comment]
I have similar problems. Setting the values by code when I have ranges close to each other results in corrupted data

Code to reproduce:

var bar = RangeBar({
  min: 0,
  max: 24*60,
  values: [
      [240,480],
      [495, 555],
      [720,960]
  ],
  label: function(a){return a},
});

bar.val([[240,540],[720,960]]); //First range will be 195-495 and if dragging that intervall with the mouse it gets a lot wider

**Comment by quarterto** [comment]
Values from `.val` should not be considered reliable until the bar has had chance to flush its changes to the DOM. `requestAnimationFrame` or `setTimeout(0)` should achieve this. I appreciate it feels kludgy but there's no real way to propagate the `val` changes through the bar synchronously.
