### ISSUE TITLE
Demo uses deprecated non-ISO strings, might break soon (moment.js warning)

### ISSUE THREAD

**Issue by valioDOTch** [quarterto/Elessar#95]
When running the demo, the following error pops up in the console

    Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

This is caused by the "LLLL" format which is passed to valueParse.

**Comment by quarterto** [comment]
Well, I don't plan to update Moment in the demo any time soon :smile: the demo needs an overhaul anyway. Thanks for reporting.
