### ISSUE TITLE
Touch events not working?

### ISSUE THREAD

**Issue by praneybehl** [quarterto/Elessar#96]
I just tried to navigate the elessar demo and another one I did on a couple of mobile devices and nothing seems to work.

Doesn't elessar support touch events?

**Comment by quarterto** [comment]
Touch events should work. Which browsers/devices are you using?

**Comment by praneybehl** [comment]
I have tried samsung note 4 running on Android 5.01, Nexus 4 on Android 4,4,2 and also LG G3 on V 5.0.1 none working.
Even when I try to simulate mobile in Chrome it doesn't work either.

**Comment by praneybehl** [comment]
Ok just did another test, and installed firefox and opera on the phones and still doesn't work in any of them.

**Comment by praneybehl** [comment]
Just wondering if I'm the only one getting the issue?

**Comment by praneybehl** [comment]
@quarterto Did you get around checking the issue?

**Comment by quarterto** [comment]
Not had chance to test this yet. I'll have a look this weekend.

**Comment by praneybehl** [comment]
@quarterto Thanks appreciate it mate :+1:

**Comment by praneybehl** [comment]
@quarterto Did you get a chance to have look at the issue?

**Comment by quarterto** [comment]
I can confirm this with Chrome touch emulation on 1.8.3.

**Comment by quarterto** [comment]
Fixed in 1.8.4.

**Comment by praneybehl** [comment]
Thanks mate working on chrome emulation, i'll check the reset tomorrow.
Thanks again.
